#!/bin/bash

set -euo pipefail

USER_HOME="${HOME:-/home/xmyf}"
SLIME_DIR="${SLIME_DIR:-${USER_HOME}/slime}"

# Edit the defaults below, or override them inline, for example:
#   NUM_EPOCH=1 LR=5e-7 TRAIN_GPU_IDS=4,5,6,7 bash scripts/launch-qwen3-32B-liveweb-sft-debug.sh

RUN_STAMP="${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}"
SESSION_NAME="${SESSION_NAME:-slime_liveweb_sft_debug_${RUN_STAMP}}"
RUN_DIR="${RUN_DIR:-${USER_HOME}/slime_runs/${SESSION_NAME}}"

TRAIN_GPU_IDS="${TRAIN_GPU_IDS:-0,1,2,3,4,5,6,7}"
TRAIN_TP_SIZE="${TRAIN_TP_SIZE:-8}"
TRAIN_PP_SIZE="${TRAIN_PP_SIZE:-1}"
EVAL_GPU_IDS="${EVAL_GPU_IDS:-0,1,2,3,4,5,6,7}"
ARENA_EVAL_MODE="${ARENA_EVAL_MODE:-watch}"
SKIP_ARENA_EVAL="${SKIP_ARENA_EVAL:-1}"
SKIP_INITIAL_EVAL="${SKIP_INITIAL_EVAL:-0}"

WANDB_PROJECT="${WANDB_PROJECT:-slime-liveweb}"
WANDB_GROUP="${WANDB_GROUP:-${SESSION_NAME}}"

NUM_EPOCH="${NUM_EPOCH:-1}"
ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-32}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-32}"
LR="${LR:-1e-6}"
MIN_LR="${MIN_LR:-1e-7}"
MAX_TOKENS_PER_GPU="${MAX_TOKENS_PER_GPU:-2048}"
ROLLOUT_MAX_PROMPT_LEN="${ROLLOUT_MAX_PROMPT_LEN:-32768}"
SAVE_INTERVAL_OVERRIDE="${SAVE_INTERVAL_OVERRIDE:-}"

FILTER_COUNT_SAMPLE_SIZE="${FILTER_COUNT_SAMPLE_SIZE:-128}"
FILTERED_DATASET_ROWS_OVERRIDE="${FILTERED_DATASET_ROWS_OVERRIDE:-}"
MIN_TRAIN_GPU_FREE_MEM_MB="${MIN_TRAIN_GPU_FREE_MEM_MB:-70000}"

SERVER_PORT="${SERVER_PORT:-31000}"
RAY_HEAD_PORT="${RAY_HEAD_PORT:-6382}"
RAY_DASHBOARD_PORT="${RAY_DASHBOARD_PORT:-8266}"

DATASET_PATH="${DATASET_PATH:-${USER_HOME}/liveweb_hf_dataset_score_1/data/train.parquet}"
HF_MODEL_DIR="${HF_MODEL_DIR:-${USER_HOME}/Qwen3-32B}"
REF_LOAD_DIR="${REF_LOAD_DIR:-${USER_HOME}/Qwen3-32B_torch_dist_tp${TRAIN_TP_SIZE}_pp${TRAIN_PP_SIZE}}"
LIVEWEB_ARENA_DIR="${LIVEWEB_ARENA_DIR:-${USER_HOME}/liveweb-arena}"

cat <<EOF
Launching debug run with:
  SESSION_NAME=${SESSION_NAME}
  RUN_DIR=${RUN_DIR}
  TRAIN_GPU_IDS=${TRAIN_GPU_IDS}
  TRAIN_TP_SIZE=${TRAIN_TP_SIZE}
  TRAIN_PP_SIZE=${TRAIN_PP_SIZE}
  EVAL_GPU_IDS=${EVAL_GPU_IDS}
  ARENA_EVAL_MODE=${ARENA_EVAL_MODE}
  SKIP_ARENA_EVAL=${SKIP_ARENA_EVAL}
  SKIP_INITIAL_EVAL=${SKIP_INITIAL_EVAL}
  NUM_EPOCH=${NUM_EPOCH}
  ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE}
  GLOBAL_BATCH_SIZE=${GLOBAL_BATCH_SIZE}
  LR=${LR}
  MIN_LR=${MIN_LR}
  MAX_TOKENS_PER_GPU=${MAX_TOKENS_PER_GPU}
  ROLLOUT_MAX_PROMPT_LEN=${ROLLOUT_MAX_PROMPT_LEN}
  SAVE_INTERVAL_OVERRIDE=${SAVE_INTERVAL_OVERRIDE}
  FILTERED_DATASET_ROWS_OVERRIDE=${FILTERED_DATASET_ROWS_OVERRIDE}
  MIN_TRAIN_GPU_FREE_MEM_MB=${MIN_TRAIN_GPU_FREE_MEM_MB}
  WANDB_GROUP=${WANDB_GROUP}
EOF

export SLIME_DIR
export RUN_STAMP
export SESSION_NAME
export RUN_DIR
export TRAIN_GPU_IDS
export TRAIN_TP_SIZE
export TRAIN_PP_SIZE
export EVAL_GPU_IDS
export ARENA_EVAL_MODE
export SKIP_ARENA_EVAL
export SKIP_INITIAL_EVAL
export WANDB_PROJECT
export WANDB_GROUP
export NUM_EPOCH
export ROLLOUT_BATCH_SIZE
export GLOBAL_BATCH_SIZE
export LR
export MIN_LR
export MAX_TOKENS_PER_GPU
export ROLLOUT_MAX_PROMPT_LEN
export SAVE_INTERVAL_OVERRIDE
export FILTER_COUNT_SAMPLE_SIZE
export FILTERED_DATASET_ROWS_OVERRIDE
export MIN_TRAIN_GPU_FREE_MEM_MB
export SERVER_PORT
export RAY_HEAD_PORT
export RAY_DASHBOARD_PORT
export DATASET_PATH
export HF_MODEL_DIR
export REF_LOAD_DIR
export LIVEWEB_ARENA_DIR

bash "${SLIME_DIR}/scripts/launch-qwen3-32B-liveweb-sft-tmux.sh"
