#!/bin/bash

set -euo pipefail

USER_HOME="${HOME:-/home/xmyf}"
SLIME_DIR="${SLIME_DIR:-${USER_HOME}/slime}"
TRAIN_PHASE="${TRAIN_PHASE:-warmup}"
TRAIN_MEMORY_MARGIN_BYTES="${TRAIN_MEMORY_MARGIN_BYTES:-0}"
NUM_ROLLOUT_OVERRIDE_VALUE="${NUM_ROLLOUT_OVERRIDE:-}"
SAVE_INTERVAL_OVERRIDE_VALUE="${SAVE_INTERVAL_OVERRIDE:-}"
EVAL_INTERVAL_OVERRIDE_VALUE="${EVAL_INTERVAL_OVERRIDE:-}"
HF_MODEL_DIR_VALUE="${HF_MODEL_DIR:-}"
REF_LOAD_DIR_VALUE="${REF_LOAD_DIR:-}"
LOAD_CHECKPOINT_DIR_VALUE="${LOAD_CHECKPOINT_DIR:-}"
RESUME_CHECKPOINT_DIR_VALUE="${RESUME_CHECKPOINT_DIR:-}"
LIVEWEB_RUN_MODE_VALUE="${LIVEWEB_RUN_MODE:-}"
LIVEWEB_RESUME_MODE_VALUE="${LIVEWEB_RESUME_MODE:-}"
ROLLOUT_BATCH_SIZE_VALUE="${ROLLOUT_BATCH_SIZE:-}"
N_SAMPLES_PER_PROMPT_VALUE="${N_SAMPLES_PER_PROMPT:-}"
GLOBAL_BATCH_SIZE_VALUE="${GLOBAL_BATCH_SIZE:-}"
TRAIN_DYNAMIC_GLOBAL_BATCH_SIZE_CAP_VALUE="${TRAIN_DYNAMIC_GLOBAL_BATCH_SIZE_CAP:-}"
TRAIN_MIN_DYNAMIC_GLOBAL_BATCH_SIZE_VALUE="${TRAIN_MIN_DYNAMIC_GLOBAL_BATCH_SIZE:-}"
LIVEWEB_MAX_COMPLETION_TOKENS_VALUE="${LIVEWEB_MAX_COMPLETION_TOKENS:-}"
RL_DEFAULT_MAX_COMPLETION_TOKENS_VALUE="${RL_DEFAULT_MAX_COMPLETION_TOKENS:-}"
LIVEWEB_RL_SAMPLE_WALL_TIMEOUT_SECONDS_VALUE="${LIVEWEB_RL_SAMPLE_WALL_TIMEOUT_SECONDS:-}"
LIVEWEB_RL_ROLLOUT_ROUND_TIMEOUT_SECONDS_VALUE="${LIVEWEB_RL_ROLLOUT_ROUND_TIMEOUT_SECONDS:-}"
MAX_STEPS_VALUE="${MAX_STEPS:-}"
LIVEWEB_SKIP_SAVE_WARMUP_VALUE="${LIVEWEB_SKIP_SAVE_WARMUP:-}"
LIVEWEB_SKIP_SAVE_MAIN_VALUE="${LIVEWEB_SKIP_SAVE_MAIN:-}"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
SESSION_NAME="${SESSION_NAME:-slime_liveweb_online_rl_${TRAIN_PHASE}_${TIMESTAMP}}"
RUN_ROOT="${RUN_ROOT:-/data/slime_runs/liveweb_online_rl_qwen3_32b_${TIMESTAMP}}"
LOG_DIR="${RUN_ROOT}/logs"
mkdir -p "${LOG_DIR}"

tmux kill-session -t "${SESSION_NAME}" >/dev/null 2>&1 || true
tmux new-session -d -s "${SESSION_NAME}" -n train
tmux send-keys -t "${SESSION_NAME}:train" "cd ${SLIME_DIR}" C-m
tmux send-keys -t "${SESSION_NAME}:train" "RUN_ROOT='${RUN_ROOT}' TRAIN_PHASE='${TRAIN_PHASE}' TRAIN_MEMORY_MARGIN_BYTES='${TRAIN_MEMORY_MARGIN_BYTES}' NUM_ROLLOUT_OVERRIDE='${NUM_ROLLOUT_OVERRIDE_VALUE}' SAVE_INTERVAL_OVERRIDE='${SAVE_INTERVAL_OVERRIDE_VALUE}' EVAL_INTERVAL_OVERRIDE='${EVAL_INTERVAL_OVERRIDE_VALUE}' HF_MODEL_DIR='${HF_MODEL_DIR_VALUE}' REF_LOAD_DIR='${REF_LOAD_DIR_VALUE}' LOAD_CHECKPOINT_DIR='${LOAD_CHECKPOINT_DIR_VALUE}' RESUME_CHECKPOINT_DIR='${RESUME_CHECKPOINT_DIR_VALUE}' LIVEWEB_RUN_MODE='${LIVEWEB_RUN_MODE_VALUE}' LIVEWEB_RESUME_MODE='${LIVEWEB_RESUME_MODE_VALUE}' ROLLOUT_BATCH_SIZE='${ROLLOUT_BATCH_SIZE_VALUE}' N_SAMPLES_PER_PROMPT='${N_SAMPLES_PER_PROMPT_VALUE}' GLOBAL_BATCH_SIZE='${GLOBAL_BATCH_SIZE_VALUE}' TRAIN_DYNAMIC_GLOBAL_BATCH_SIZE_CAP='${TRAIN_DYNAMIC_GLOBAL_BATCH_SIZE_CAP_VALUE}' TRAIN_MIN_DYNAMIC_GLOBAL_BATCH_SIZE='${TRAIN_MIN_DYNAMIC_GLOBAL_BATCH_SIZE_VALUE}' LIVEWEB_MAX_COMPLETION_TOKENS='${LIVEWEB_MAX_COMPLETION_TOKENS_VALUE}' RL_DEFAULT_MAX_COMPLETION_TOKENS='${RL_DEFAULT_MAX_COMPLETION_TOKENS_VALUE}' LIVEWEB_RL_SAMPLE_WALL_TIMEOUT_SECONDS='${LIVEWEB_RL_SAMPLE_WALL_TIMEOUT_SECONDS_VALUE}' LIVEWEB_RL_ROLLOUT_ROUND_TIMEOUT_SECONDS='${LIVEWEB_RL_ROLLOUT_ROUND_TIMEOUT_SECONDS_VALUE}' MAX_STEPS='${MAX_STEPS_VALUE}' LIVEWEB_SKIP_SAVE_WARMUP='${LIVEWEB_SKIP_SAVE_WARMUP_VALUE}' LIVEWEB_SKIP_SAVE_MAIN='${LIVEWEB_SKIP_SAVE_MAIN_VALUE}' LIVEWEB_FAILURE_BUCKET_RESULTS_DIRS=\"\${LIVEWEB_FAILURE_BUCKET_RESULTS_DIRS:-/data/liveweb_eval/affine_liveweb_base_qwen32b_tp2x2_seed42_20260322_205225/raw_results:/data/liveweb_eval/affine_liveweb_sft_qwen32b_tp2x2_seed42_20260322_205225/raw_results}\" bash ${SLIME_DIR}/scripts/run-qwen3-32B-liveweb-online-rl.sh | tee ${LOG_DIR}/train.log" C-m

echo "session=${SESSION_NAME}"
echo "run_root=${RUN_ROOT}"
