#!/usr/bin/env bash
set -euo pipefail

USER_HOME="${USER_HOME:-/home/xmyf}"
SLIME_HOME="${SLIME_HOME:-${USER_HOME}/slime}"
LIVEWEB_ARENA_DIR="${LIVEWEB_ARENA_DIR:-${USER_HOME}/liveweb-arena}"

BASE_MODEL_LABEL="${BASE_MODEL_LABEL:-base_qwen3_32b_mcp}"
BASE_MODEL_DIR="${BASE_MODEL_DIR:-${USER_HOME}/Qwen3-32B}"

NUM_EVAL_RUNS="${NUM_EVAL_RUNS:-25}"
NUM_TASKS_PER_RUN="${NUM_TASKS_PER_RUN:-4}"
MAX_STEPS="${MAX_STEPS:-30}"
CONTEXT_LENGTH="${CONTEXT_LENGTH:-32768}"
TEMPERATURE="${TEMPERATURE:-0.0}"
TIMEOUT_SECONDS="${TIMEOUT_SECONDS:-1800}"
START_SEED="${START_SEED:-1001}"
MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-0.95}"
TOOL_CALL_PARSER="${TOOL_CALL_PARSER:-qwen}"
REASONING_PARSER="${REASONING_PARSER:-}"
CHAT_TEMPLATE="${CHAT_TEMPLATE:-}"
API_KEY_LOCAL="${API_KEY_LOCAL:-local-liveweb}"
LIVEWEB_MAX_COMPLETION_TOKENS="${LIVEWEB_MAX_COMPLETION_TOKENS:-1024}"
LIVEWEB_ENABLE_THINKING="${LIVEWEB_ENABLE_THINKING:-}"
LIVEWEB_SEPARATE_REASONING="${LIVEWEB_SEPARATE_REASONING:-}"
LIVEWEB_IGNORE_HTTPS_ERRORS="${LIVEWEB_IGNORE_HTTPS_ERRORS:-1}"
LIVEWEB_PREFETCH_TIMEOUT_NAV="${LIVEWEB_PREFETCH_TIMEOUT_NAV:-12}"
LIVEWEB_PREFETCH_TIMEOUT_DATA="${LIVEWEB_PREFETCH_TIMEOUT_DATA:-25}"
LIVEWEB_CACHE_ALLOW_STALE="${LIVEWEB_CACHE_ALLOW_STALE:-1}"
LIVEWEB_CACHE_STALE_MAX_AGE="${LIVEWEB_CACHE_STALE_MAX_AGE:-86400}"
LIVEWEB_MAX_CACHE_FETCHES="${LIVEWEB_MAX_CACHE_FETCHES:-6}"
LIVEWEB_CACHE_DOMAIN_LIMIT_DEFAULT="${LIVEWEB_CACHE_DOMAIN_LIMIT_DEFAULT:-2}"
LIVEWEB_CACHE_DOMAIN_LIMIT_COINGECKO="${LIVEWEB_CACHE_DOMAIN_LIMIT_COINGECKO:-1}"
LIVEWEB_CACHE_DOMAIN_LIMIT_STOOQ="${LIVEWEB_CACHE_DOMAIN_LIMIT_STOOQ:-1}"
LIVEWEB_CACHE_DOMAIN_LIMIT_NEWS_YCOMBINATOR="${LIVEWEB_CACHE_DOMAIN_LIMIT_NEWS_YCOMBINATOR:-2}"
LIVEWEB_CACHE_DOMAIN_LIMIT_TAOSTATS="${LIVEWEB_CACHE_DOMAIN_LIMIT_TAOSTATS:-2}"

SERVER_SPECS="${SERVER_SPECS:-0:31050 1:31051 2:31052 3:31053 4:31054 5:31055 6:31056 7:31057}"
EVAL_CONCURRENCY_PER_SERVER="${EVAL_CONCURRENCY_PER_SERVER:-6}"
MAX_BROWSER_SESSIONS="${MAX_BROWSER_SESSIONS:-}"
MAX_LLM_REQUESTS="${MAX_LLM_REQUESTS:-}"
ROUTE_POLICY="${ROUTE_POLICY:-sticky_steal}"
STICKY_SLACK="${STICKY_SLACK:-0}"
STICKY_LATENCY_SLACK_S="${STICKY_LATENCY_SLACK_S:-10}"
CACHE_MODE="${CACHE_MODE:-shared}"
CACHE_PROFILE="${CACHE_PROFILE:-hot}"
SCHEDULE_UNIT="${SCHEDULE_UNIT:-run}"
TEMPLATES_JSON="${TEMPLATES_JSON:-}"
PREWARM_BROWSERS="${PREWARM_BROWSERS:-0}"
PREWARM_SERVERS="${PREWARM_SERVERS:-1}"
LIVEWEB_CACHE_PREFETCH_INTERVAL="${LIVEWEB_CACHE_PREFETCH_INTERVAL:-}"
SERVICE_GENERATION_ID="${SERVICE_GENERATION_ID:-${RUN_STAMP}}"
SERVICE_REQUIRE_CLEAN="${SERVICE_REQUIRE_CLEAN:-1}"
SERVICE_ACTIVITY_GRACE_S="${SERVICE_ACTIVITY_GRACE_S:-20}"

RUN_STAMP="${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}"
OUT_ROOT="${OUT_ROOT:-${USER_HOME}/slime_runs/liveweb_base_mcp_eval_${RUN_STAMP}}"
OUT_DIR="${OUT_DIR:-${OUT_ROOT}/${BASE_MODEL_LABEL}}"
PERSISTENT_CACHE_ROOT="${PERSISTENT_CACHE_ROOT:-${LIVEWEB_ARENA_DIR}/.cache/persistent}"
CACHE_ROOT="${CACHE_ROOT:-${PERSISTENT_CACHE_ROOT}}"
LOG_DIR="${LOG_DIR:-${OUT_ROOT}/logs}"
SERVICE_ROOT="${SERVICE_ROOT:-${USER_HOME}/slime_runs/liveweb_sglang_services/qwen3_32b_tp1}"
SERVER_POOL_FILE="${SERVER_POOL_FILE:-${SERVICE_ROOT}/server_pool.json}"

mkdir -p "${OUT_DIR}" "${CACHE_ROOT}" "${LOG_DIR}" "${SERVICE_ROOT}"

source "${USER_HOME}/.venvs/slime/bin/activate"

server_count=$(wc -w <<< "${SERVER_SPECS}")
if [[ -z "${MAX_BROWSER_SESSIONS}" ]]; then
  MAX_BROWSER_SESSIONS=$(( server_count * EVAL_CONCURRENCY_PER_SERVER * 2 ))
fi
if [[ -z "${MAX_LLM_REQUESTS}" ]]; then
  MAX_LLM_REQUESTS=$(( server_count * EVAL_CONCURRENCY_PER_SERVER ))
fi

if [[ "${CACHE_MODE}" == "shared" ]]; then
  LIVEWEB_CACHE_DIR="${CACHE_ROOT}/shared"
else
  LIVEWEB_CACHE_DIR="${CACHE_ROOT}/${BASE_MODEL_LABEL}"
fi
mkdir -p "${LIVEWEB_CACHE_DIR}"

python3 "${SLIME_HOME}/scripts/liveweb_sglang_service_manager.py" start \
  --service-root "${SERVICE_ROOT}" \
  --server-specs "${SERVER_SPECS}" \
  --model-dir "${BASE_MODEL_DIR}" \
  --served-model-name qwen3-32b-liveweb-eval \
  --context-length "${CONTEXT_LENGTH}" \
  --mem-fraction-static "${MEM_FRACTION_STATIC}" \
  --generation-id "${SERVICE_GENERATION_ID}" \
  $( [[ "${SERVICE_REQUIRE_CLEAN}" == "1" ]] && printf '%s' '--require-clean' ) \
  --activity-grace-s "${SERVICE_ACTIVITY_GRACE_S}" \
  $( [[ -n "${TOOL_CALL_PARSER}" ]] && printf -- '--tool-call-parser %q ' "${TOOL_CALL_PARSER}" ) \
  $( [[ -n "${REASONING_PARSER}" ]] && printf -- '--reasoning-parser %q ' "${REASONING_PARSER}" ) \
  $( [[ -n "${CHAT_TEMPLATE}" ]] && printf -- '--chat-template %q ' "${CHAT_TEMPLATE}" ) \
  --api-key "${API_KEY_LOCAL}" \
  > "${LOG_DIR}/service_start.json"

cd "${LIVEWEB_ARENA_DIR}"
export LIVEWEB_MAX_COMPLETION_TOKENS
export LIVEWEB_ENABLE_THINKING
export LIVEWEB_SEPARATE_REASONING
export LIVEWEB_IGNORE_HTTPS_ERRORS
export LIVEWEB_CACHE_DIR
export LIVEWEB_PREFETCH_TIMEOUT_NAV
export LIVEWEB_PREFETCH_TIMEOUT_DATA
export LIVEWEB_CACHE_ALLOW_STALE
export LIVEWEB_CACHE_STALE_MAX_AGE
export LIVEWEB_MAX_CACHE_FETCHES
export LIVEWEB_CACHE_DOMAIN_LIMIT_DEFAULT
export LIVEWEB_CACHE_DOMAIN_LIMIT_COINGECKO
export LIVEWEB_CACHE_DOMAIN_LIMIT_STOOQ
export LIVEWEB_CACHE_DOMAIN_LIMIT_NEWS_YCOMBINATOR
export LIVEWEB_CACHE_DOMAIN_LIMIT_TAOSTATS
if [[ -z "${LIVEWEB_CACHE_PREFETCH_INTERVAL}" ]]; then
  if [[ "${CACHE_PROFILE}" == "hot" ]]; then
    export LIVEWEB_CACHE_PREFETCH_INTERVAL="0.1"
  else
    export LIVEWEB_CACHE_PREFETCH_INTERVAL="0.5"
  fi
else
  export LIVEWEB_CACHE_PREFETCH_INTERVAL
fi

python3 "${SLIME_HOME}/scripts/liveweb_arena_dynamic_batch_runner.py" \
  --liveweb-arena-dir "${LIVEWEB_ARENA_DIR}" \
  --result-dir "${OUT_DIR}" \
  --progress-log "${LOG_DIR}/progress.log" \
  --summary-path "${OUT_ROOT}/summary.json" \
  --server-pool-file "${SERVER_POOL_FILE}" \
  --model-name "qwen3-32b-liveweb-eval" \
  --api-key "${API_KEY_LOCAL}" \
  --num-runs "${NUM_EVAL_RUNS}" \
  --start-seed "${START_SEED}" \
  --num-tasks "${NUM_TASKS_PER_RUN}" \
  --max-steps "${MAX_STEPS}" \
  --timeout "${TIMEOUT_SECONDS}" \
  --temperature "${TEMPERATURE}" \
  --cache-dir "${LIVEWEB_CACHE_DIR}" \
  --mode eval \
  --cache-profile "${CACHE_PROFILE}" \
  --schedule-unit "${SCHEDULE_UNIT}" \
  $( [[ -n "${TEMPLATES_JSON}" ]] && printf -- '--templates-json %q ' "${TEMPLATES_JSON}" ) \
  --route-policy "${ROUTE_POLICY}" \
  --sticky-slack "${STICKY_SLACK}" \
  --sticky-latency-slack-s "${STICKY_LATENCY_SLACK_S}" \
  --max-browser-sessions "${MAX_BROWSER_SESSIONS}" \
  --max-llm-requests "${MAX_LLM_REQUESTS}" \
  $( [[ "${PREWARM_BROWSERS}" == "1" ]] && printf '%s' '--prewarm-browsers' ) \
  $( [[ "${PREWARM_SERVERS}" == "1" ]] && printf '%s' '--prewarm-servers' )
